"""Schemas package - exports all Pydantic models from consolidated schema files."""

# Enums (kept separate as used across domains)
from app.schemas.enums import (
    RetailArchetype,
    ReplenishmentStrategy,
    LocationTier,
    FashionTier,
    StoreFormat,
    Region,
    MarkdownStatus,
    WorkflowStatus
)

# Forecast domain (forecast, allocation, markdown)
from app.schemas.forecast_schemas import (
    WeeklyDemand,
    ClusterDistribution,
    ForecastBase,
    ForecastCreate,
    Forecast,
    StoreAllocation,
    AllocationBase,
    AllocationCreate,
    AllocationPlan,
    MarkdownBase,
    MarkdownCreate,
    MarkdownDecision,
    MarkdownRequest,
)

# Workflow domain (workflow, approval, parameters, websocket)
from app.schemas.workflow_schemas import (
    SeasonParameters,
    ParameterExtractionRequest,
    ParameterExtractionResponse,
    WorkflowCreateRequest,
    ReforecastRequest,
    WorkflowResponse,
    WorkflowStatusResponse,
    WorkflowResultsResponse,
    ManufacturingApprovalRequest,
    ManufacturingApprovalResponse,
    MarkdownApprovalRequest,
    MarkdownApprovalResponse,
    AgentStartedMessage,
    AgentProgressMessage,
    AgentCompletedMessage,
    HumanInputRequiredMessage,
    WorkflowCompleteMessage,
    ErrorMessage,
    WebSocketMessage,
)

# Data domain (category, store, upload, variance)
from app.schemas.data_schemas import (
    CategoryBase,
    CategoryCreate,
    Category,
    CategorySummary,
    StoreClusterBase,
    StoreClusterCreate,
    StoreCluster,
    ClusterSummary,
    StoreBase,
    StoreCreate,
    Store,
    StoreDetail,
    HistoricalSalesUploadResponse,
    VarianceCheckResult,
    WeeklySalesUploadResponse,
    VarianceAnalysisDetail,
)

__all__ = [
    # Enums
    "RetailArchetype",
    "ReplenishmentStrategy",
    "LocationTier",
    "FashionTier",
    "StoreFormat",
    "Region",
    "MarkdownStatus",
    "WorkflowStatus",
    # Forecast domain
    "WeeklyDemand",
    "ClusterDistribution",
    "ForecastBase",
    "ForecastCreate",
    "Forecast",
    "StoreAllocation",
    "AllocationBase",
    "AllocationCreate",
    "AllocationPlan",
    "MarkdownBase",
    "MarkdownCreate",
    "MarkdownDecision",
    "MarkdownRequest",
    # Workflow domain
    "SeasonParameters",
    "ParameterExtractionRequest",
    "ParameterExtractionResponse",
    "WorkflowCreateRequest",
    "ReforecastRequest",
    "WorkflowResponse",
    "WorkflowStatusResponse",
    "WorkflowResultsResponse",
    "ManufacturingApprovalRequest",
    "ManufacturingApprovalResponse",
    "MarkdownApprovalRequest",
    "MarkdownApprovalResponse",
    "AgentStartedMessage",
    "AgentProgressMessage",
    "AgentCompletedMessage",
    "HumanInputRequiredMessage",
    "WorkflowCompleteMessage",
    "ErrorMessage",
    "WebSocketMessage",
    # Data domain
    "CategoryBase",
    "CategoryCreate",
    "Category",
    "CategorySummary",
    "StoreClusterBase",
    "StoreClusterCreate",
    "StoreCluster",
    "ClusterSummary",
    "StoreBase",
    "StoreCreate",
    "Store",
    "StoreDetail",
    "HistoricalSalesUploadResponse",
    "VarianceCheckResult",
    "WeeklySalesUploadResponse",
    "VarianceAnalysisDetail",
]
